models/User.php
<?php

namespace app\models;

use Yii;

class User extends \app\components\CActiveRecord implements \yii\web\IdentityInterface {

    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    public static function tableName() {
        return 'rbac_usuarios';
    }

    public static function getDb() {
        return Yii::$app->db2;
    }

    public static function findIdentity($id) {

         return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null) {

        return static::findOne(['access_token' => $token]);

    }

    public static function findByUsername($username) {

        return static::findOne(['nombreusuario' => $username]);
        
    }

    public function getId() {
        return $this->getPrimaryKey();
    }

    public function getAuthKey() {
        return $this->authKey;
    }

    public function validateAuthKey($authKey) {
        return $this->authKey === $authKey;
    }

    public function validatePassword($password) {
        return \Yii::$app->getSecurity()->validatePassword($password,$this->contrasena);
    }

    public function getNameFull(){
        return $this->nombre.' '.$this->apellido;
    }

}

views/layouts/complete/_menu.php
<?php 
use yii\helpers\Html;
use yii\helpers\Url;
use app\modules\accesos\models\RBACRolesOpciones;
use app\modules\accesos\models\RBACRolesOpcionesUsuarios;
?>
<?php
    $menuSQL = RBACRolesOpcionesUsuarios::find()
                    ->alias('t')
                    ->where([
                        'm.categoria' => 'main',
                        't.estatus' => \app\components\CActiveRecord::STATUS_ACTIVE,
                        'o.estatus' => \app\components\CActiveRecord::STATUS_ACTIVE,
                        'm.estatus' => \app\components\CActiveRecord::STATUS_ACTIVE,
                        'r.estatus' => \app\components\CActiveRecord::STATUS_ACTIVE,
                        't.id_rbac_usuario' => \Yii::$app->user->identity->id_rbac_usuario,
                    ])
                    ->joinWith(['idRbacRolOpcion r',])
                    ->joinWith(['idRbacRolOpcion.idRbacMenuOpcion o'])
                    ->joinWith(['idRbacRolOpcion.idRbacMenuOpcion.idMenu m'])
                    ->orderBy(['m.jerarquia' => SORT_ASC, 'm.orden' => SORT_ASC, 'o.orden' => SORT_ASC])
                    ->all();

    $menuSQL = RBACRolesOpciones::find()
                    ->alias('t')
                    ->where([
                        'm.categoria' => 'main',
                        't.estatus' => \app\components\CActiveRecord::STATUS_ACTIVE,
                        'o.estatus' => \app\components\CActiveRecord::STATUS_ACTIVE,
                        'm.estatus' => \app\components\CActiveRecord::STATUS_ACTIVE,
                        't.id_rbac_rol' => \Yii::$app->user->identity->id_rbac_rol,
                    ])
                    ->joinWith(['idRbacMenuOpcion o','idRbacMenuOpcion.idMenu m'])
                    ->orderBy(['m.jerarquia' => SORT_ASC, 'm.orden' => SORT_ASC, 'o.orden' => SORT_ASC])
                    ->all();

    $menus = [];
    $menul1 = [];
    $menul2 = [];
    $menul3 = [];

    foreach ($menuSQL as $m) {
        $usuariositem = RBACRolesOpcionesUsuarios::find()
            ->where([
                'estatus' => \app\components\CActiveRecord::STATUS_INACTIVE,
                'id_rbac_usuario' => \Yii::$app->user->identity->id_rbac_usuario,
                'id_rbac_rol_opcion' => $m->id_rbac_rol_opcion
            ])->one();

        if(!$usuariositem) {
            $id_rbac_menu = $m->idRbacMenuOpcion->idMenu->id_rbac_menu;
            $jerarquia = $m->idRbacMenuOpcion->idMenu->jerarquia;
            if ($m->idRbacMenuOpcion->idMenu->nivel == 1) {
                $menul1[$id_rbac_menu]['data'] = NULL;
                $menul1[$id_rbac_menu]['menu_id'] = $m->idRbacMenuOpcion->idMenu->id_rbac_menu;
                $menul1[$id_rbac_menu]['menu_descripcion'] = $m->idRbacMenuOpcion->idMenu->descripcion;
                $menul1[$id_rbac_menu]['menu_url'] = $m->idRbacMenuOpcion->idMenu->url;
                $menul1[$id_rbac_menu]['menu_url_tipo'] = $m->idRbacMenuOpcion->idMenu->url_tipo;
                $menul1[$id_rbac_menu]['menu_icono'] = $m->idRbacMenuOpcion->idMenu->icono;
                $menul1[$id_rbac_menu]['menu_modulo'] = $m->idRbacMenuOpcion->idMenu->modulo;
                $menul1[$id_rbac_menu]['menu_jerarquia'] = $m->idRbacMenuOpcion->idMenu->jerarquia;
            }
            if ($m->idRbacMenuOpcion->idMenu->nivel == 2) {
                $menul2[$jerarquia]['data'][$id_rbac_menu]['menu_id'] = $m->idRbacMenuOpcion->idMenu->id_rbac_menu;
                $menul2[$jerarquia]['data'][$id_rbac_menu]['menu_descripcion'] = $m->idRbacMenuOpcion->idMenu->descripcion;
                $menul2[$jerarquia]['data'][$id_rbac_menu]['menu_url'] = $m->idRbacMenuOpcion->idMenu->url;
                $menul2[$jerarquia]['data'][$id_rbac_menu]['menu_url_tipo'] = $m->idRbacMenuOpcion->idMenu->url_tipo;
                $menul2[$jerarquia]['data'][$id_rbac_menu]['menu_icono'] = $m->idRbacMenuOpcion->idMenu->icono;
                $menul2[$jerarquia]['data'][$id_rbac_menu]['menu_modulo'] = $m->idRbacMenuOpcion->idMenu->modulo;
                $menul2[$jerarquia]['data'][$id_rbac_menu]['menu_jerarquia'] = $m->idRbacMenuOpcion->idMenu->jerarquia;
            }
            if ($m->idRbacMenuOpcion->idMenu->nivel == 3) {
                $menul3[$jerarquia]['data'][$id_rbac_menu]['menu_descripcion'] = $m->idRbacMenuOpcion->idMenu->descripcion;
                $menul3[$jerarquia]['data'][$id_rbac_menu]['menu_url'] = $m->idRbacMenuOpcion->idMenu->url;
                $menul3[$jerarquia]['data'][$id_rbac_menu]['menu_url_tipo'] = $m->idRbacMenuOpcion->idMenu->url_tipo;
                $menul3[$jerarquia]['data'][$id_rbac_menu]['menu_icono'] = $m->idRbacMenuOpcion->idMenu->icono;
                $menul3[$jerarquia]['data'][$id_rbac_menu]['menu_modulo'] = $m->idRbacMenuOpcion->idMenu->modulo;
                $menul3[$jerarquia]['data'][$id_rbac_menu]['menu_jerarquia'] = $m->idRbacMenuOpcion->idMenu->jerarquia;
            }
        }
    }
?> 
<ul class='wraplist' style="min-height: 92%;height: auto;">   
    <li class="menusection"><?= Yii::t('app','menu') ?></li>
        <?php  foreach ($menul1 as $m) : ?>
            <?php if (count(@$menul2[$m['menu_id']]['data']) > 0) {
                    $row = '<span class="arrow "></span> ';
                    $url = '#';
                } else {
                    $url = Yii::getAlias('@web/'.$m['menu_url']);
                    $row = '';
                }
                $url_index = explode('/', $m['menu_url']);
            ?>
            <li class="<?= \Yii::$app->controller->id == $url_index[0] ? 'open' : '' ?>">
                <?= Html::a($m['menu_icono'] . ' <span class="title">' . $m['menu_descripcion']. '</span>' . $row, $url) ?>
                <?php if (count(@$menul2[$m['menu_id']]['data']) > 0) : ?>
                <ul class="sub-menu" >
                    <?php foreach ($menul2[$m['menu_id']]['data'] as $ml2) : ?>
                        <?php if (count(@$menul3[$ml2['menu_id']]['data']) > 0) {
                            $rowL2 = '<span class="arrow "></span>';
                            $urlL2 = 'javascript:;';
                        } else {
                            $rowL2 = '';
                            $urlL2 = $ml2['menu_url'];
                        } 
                        $url_index2 = explode('/', $ml2['menu_url']);
                        $active_url = \Yii::$app->controller->id == $url_index2[1] ? 'active' : '';
                        ?>
                        <li>
                            <?= Html::a($ml2['menu_icono'] . ' <span class="title">' . $ml2['menu_descripcion']. '</span>' . $rowL2, Yii::getAlias('@web/'.$urlL2),['class' => $active_url]) ?>
                            <?php if (count(@$menul3[$ml2['menu_id']]['data']) > 0) :?>
                                <ul class="sub-menu">
                                    <?php foreach ($menul3[$ml2['menu_id']]['data'] as $ml3) : ?>
                                        <li>
                                            <?php $class_active = 'active'; ?>
                                            <?= Html::a($ml3['menu_icono'] . ' <span class="title">' . $ml3['menu_descripcion']. '</span>' , Yii::getAlias('@web/'.$ml3['menu_url'])) ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </li>
                    <?php endforeach;?>
                </ul>
                <?php endif;?>
            </li>
        <?php endforeach; ?>
</ul>

views/layouts/complete/_menu_user.php
<?php 
use yii\helpers\Html;
use app\modules\accesos\models\RBACMenus;
?>
<?php
    $menuSQL = RBACMenus::find()
                    ->where([
                        'categoria' => 'main_user',
                    ])
                    ->orderBy(['jerarquia' => SORT_ASC, 'orden' => SORT_ASC])
                    ->all();
    $menus = [];
    foreach ($menuSQL as $m) {
        $menus[$m->id_rbac_menu]['data'] = NULL;
        $menus[$m->id_rbac_menu]['menu_id'] = $m->id_rbac_menu;
        $menus[$m->id_rbac_menu]['menu_descripcion'] = $m->descripcion;
        $menus[$m->id_rbac_menu]['menu_url'] = $m->url;
        $menus[$m->id_rbac_menu]['menu_url_tipo'] = $m->url_tipo;
        $menus[$m->id_rbac_menu]['menu_icono'] = $m->icono;
        $menus[$m->id_rbac_menu]['menu_modulo'] = $m->modulo;
        $menus[$m->id_rbac_menu]['menu_jerarquia'] = $m->jerarquia;
    }
    $contador = count($menus);
    $i = 1;
?>
<ul class="dropdown-menu profile animated fadeIn">
    <?php foreach ($menus as $m) : ?>
    <li <?= $contador == $i ? 'class="last"': ''; ?>>
        <?= Html::a($m['menu_icono'] . Yii::t('app',$m['menu_descripcion']), Yii::getAlias('@web/'.$m['menu_url'])) ?>
    </li>
    <?php $i++;?>
    <?php endforeach; ?>
</ul>

views/layouts/complete/main.php
<?php

use app\assets\AppAsset;
use yii\helpers\Html;
use yii\web\View;
use yii\helpers\Url;

AppAsset::register($this);
$this->beginPage()
?>
<!DOCTYPE html>
<html class=" ">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title><?= Yii::$app->name ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
<?php $this->head() ?>
</head>
    <body class=" ">
<?php $this->beginBody() ?>
        <div class='page-topbar '>
            <div class='logo-area'>
            </div>
            <div class='quick-area'>
                <div class='pull-left'>
                    <ul class="info-menu left-links list-inline list-unstyled">
                        <li class="sidebar-toggle-wrap">
                            <a href="#" data-toggle="sidebar" class="sidebar_toggle">
                                <i class="fa fa-bars"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class='pull-right'>
                    <ul class="info-menu right-links list-inline list-unstyled">
                        <li class="profile">
                            <a href="#" data-toggle="dropdown" class="toggle">
                                <img src="<?php echo Yii::getAlias('@web/images/avatar1.jpg') ?>" alt="user-image" class="img-circle img-inline">
                                <span><?= \Yii::$app->user->identity->nameFull ?> <i class="fa fa-angle-down"></i></span>
                            </a>
                            <?php echo $this->render('_menu_user'); ?>
                        </li>
                        <li class="chat-toggle-wrapper">
                            <a href="#" data-toggle="chatbar" class="toggle_chat">
                                <i class="fa fa-comments"></i>
                                <span class="badge badge-accent">9</span>
                                <i class="fa fa-times"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="page-container row-fluid container-fluid">

            <div class="page-sidebar fixedscroll">

                <div class="page-sidebar-wrapper ps-container ps-active-y " id="main-menu-wrapper">




                    <?php echo $this->render('_menu'); ?>

                    <div class="version_">

                        <h6>
                            <abbr title="Version">
                                <?php echo Yii::$app->params['version'];?>
                            </abbr>
                    </div>

                </div>

            </div>
            <section id="main-content" class=" ">
                <section class="wrapper main-wrapper row" style=''>
<?php if (!empty(Yii::$app->params['layout.title'])): ?>
                        <div class="col-xs-12">
                            <div class="page-title">

                                <div class="pull-left">
                                    <h1 class="title"><?= Html::encode(Yii::$app->params['layout.title']) ?></h1>
                                                             </div>

                                <div class="pull-right hidden-xs">
                                </div>

                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="clearfix"></div>
<?= $content ?>

                </section>
            </section>

            <div class="chatapi-windows ">

            </div>    </div>


        <?php if (\Yii::$app->params['show.modal.delete']) { ?>

            <?php
            $this->registerJs('
                    $("body").on("click",".option-delete",function(){
                        var urlDelete = $(this).attr("href");
                        $("#form-confirm").attr("action",urlDelete);
                        $("#modal-confirm .modal-body").html("Desea eliminar este elemento?");
                        $("#modal-confirm").modal("show");
                        return false;
                    });
                    
                    $("body").on("click",".option-available",function(){
                        var urlAvailable = $(this).attr("href");
                        $("#form-confirm").attr("action",urlAvailable);
                        $("#modal-confirm .modal-body").html("Desea colocar disponible este elemento?");
                        $("#modal-confirm").modal("show");
                        return false;
                    });
                    
                    $("body").on("click",".option-clean",function(){
                        var urlClean = $(this).attr("href");
                        $("#form-confirm").attr("action",urlClean);
                        $("#modal-confirm .modal-body").html("Desea eliminar los reporte z de la máquina?");
                        $("#modal-confirm").modal("show");
                        return false;
                    });
                    
                    $("#btn-confirm-success").click(function(){
                        var url = $("#form-confirm").attr("action");
                        var _csrf="'.Yii::$app->request->getCsrfToken() .'";
                        
                        $.post( url,{ _csrf:_csrf})
                        .done(function( res ) {
                            console.log("listo1: "+url);
                        })
                        .fail(function() {
                            console.log("listo2: "+url);
                        });
                        console.log(url);
                        return false;
                    });
                            '
            );
            echo $this->render('../modals/_confirm');
        }
        $mens = '';
        foreach (Yii::$app->session->getAllFlashes() as $key => $value) {
            if (strpos($key, 'success') === false) {

            } else {
                $mens .= "showSuccess('" . $value . "');";
            }
            if (strpos($key, 'warning') === false) {

            } else {
                $mens .= "showErrorMessage('" . $value . "');";
            }
        }

        $this->registerJs($mens);

            $this->registerJs($mens);

            $this->registerJs("var dashboard_url='".Url::to(['/contribuyentes/filtro'])."'",View::POS_BEGIN);
            $this->registerJs("var social_reason_minimumInputLength = '".Yii::$app->params['filtro.social_reason.minimumInputLength']."'",View::POS_BEGIN);

        ?>
<?php $this->endBody() ?>
    </body>
</html>

<?php $this->endPage() ?>

views/layouts/complete/menu.php
<ul class="wraplist" style="min-height: 92%;height: auto;">	

    <li class='menusection'>Menú </li>

    <li class=""> 
        <a href="javascript:;">
            <i class="fa fa-spinner"></i>
            <span class="title">Logs Protocolo TXT</span>
            <span class="arrow "></span>                                
        </a>
        <ul class="sub-menu" >
            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'logpartes' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/logpartes/') ?>"  >Paquetes Recibidos</a>
            </li>
            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'log' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/log/') ?>" >Paquetes Descifrados</a>
            </li>
            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'logerror' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/logerror/') ?>"  >Paquetes Con Error</a>
            </li>



        </ul>
    </li>

    <li class=""> 
        <a href="javascript:;">
            <i class="fa fa-spinner"></i>
            <span class="title">Logs Protocolo XML</span>
            <span class="arrow "></span>                                
        </a>
        <ul class="sub-menu" >
            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'logoperacion' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/logs/logoperacion') ?>"  >Operaciones Protocolo XML</a>


            </li>


        </ul>
    </li>
    <li class="<?php echo \Yii::$app->controller->id == 'reportez' ? 'open' : '' ?>"> 
        <a href="<?php echo Yii::getAlias('@web/reportez') ?>">
            <i class="fa fa-file-text"></i>
            <span class="title">Reportes Z</span>
        </a>
    </li>

    <li class="<?php echo \Yii::$app->controller->id == 'transacciones' ? 'open' : '' ?>"> 
        <a href="<?php echo Yii::getAlias('@web/transacciones') ?>">
            <i class="fa fa-arrows-h"></i>
            <span class="title">Transacciones</span>
        </a>
    </li>

    <li class="<?php echo \Yii::$app->controller->id == 'peticiones' ? 'open' : '' ?>"> 
        <a href="<?php echo Yii::getAlias('@web/peticiones/peticiones/index') ?>">
            <i class="fa fa-exchange"></i>
            <span class="title"><?= Yii::t('app', 'requests'); ?></span>

        </a>

    </li>


    

    <li class=""> 
        <a href="javascript:;">
            <i class="fa fa-suitcase"></i>
            <span class="title">Administración</span>
            <span class="arrow "></span>                                
        </a>
        <ul class="sub-menu" >
           
            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'configuracion' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/configuracion/configuracion/index') ?>"  >Configuración Protocolo XML</a>
            </li>

            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'contribuyentes' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/contribuyentes/contribuyentes/') ?>" >Contribuyentes</a>
            </li>
            
             <li>
                <a class="<?php echo \Yii::$app->controller->id == 'firmware' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/version/firmware/index') ?>"  >Firmware</a>
            </li>            
             
            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'imobiles' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/admin/imobiles/index') ?>"  >Protocolo XML</a>
            </li>

            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'maquina' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/admin/maquina/') ?>"  >Maquinas Fiscales</a>
            </li>

            <li>
                <a class="<?php echo \Yii::$app->controller->id == 'sucursales' ? 'active' : '' ?>" href="<?php echo Yii::getAlias('@web/sucursales/sucursales/') ?>"  >Sucursales</a>
            </li>
            
             
    

        </ul>
    </li>


















</ul>