controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\data\ActiveDataProvider;
use yii\web\Response;
use yii\web\HttpException;
use yii\helpers\Url;
use app\models\ChangePassword;
use app\modules\accesos\models\RBACUsuarios;
use app\models\FormRecoverPass;
use yii\web\Session;


class SiteController extends \app\components\CController
{
   

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','view','create','update','delete'],
                'rules' => [
                    [
                        'actions' => ['index','view','create','update','delete',],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['get'],
                    'view' => ['get'],
                    'create' => ['get', 'post'],
                    'update' => ['get', 'put', 'post'],
                    'delete' => ['post', 'delete'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionIndex() {
        $this->layout = 'complete/main';
        self::logNavegacion();
        if (Yii::$app->user->isGuest) {
            $this->redirect('login');
        } else {
            return $this->render('index');
        }

    }
    public function actionLogin() {
        
       
        $this->layout = 'login/login';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            self::logNavegacion();
            return $this->goHome();
        }
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    public function actionLogout() {
        self::logNavegacion();
        Yii::$app->user->logout();
        //$this->redirect('site/login');
        return $this->goHome();
    }

    public function actionCambiar_contrasena() {

        if (Yii::$app->user->isGuest) {
            $this->redirect('login');
        }
        $this->layout = 'complete/main';
        Yii::$app->params['layout.title'] = Yii::t('app', 'myaccount');
        $model = new ChangePassword();
        if ($model->load(Yii::$app->request->post())) {
            if($model->validate()) {
                
                $user = RBACUsuarios::find()->where('id_rbac_usuario='.Yii::$app->user->identity->id_rbac_usuario)->one();
                $user->contrasena = Yii::$app->getSecurity()->generatePasswordHash($model->password_new);
                if($user->save()){
                    Yii::$app->session->setFlash('success', Yii::t('app', Yii::$app->params['message.success']));
                }else{               
                    Yii::$app->session->setFlash('warning', Yii::t('app',Yii::$app->params['message.warning']));
                }
                return $this->redirect('perfil');
            } else {
                Yii::$app->session->setFlash('warning', Yii::t('app',Yii::$app->params['message.warning']));
            }
        }
        return $this->render('change_password', [
                    'model' => $model,
        ]);
    }

    


    public function actionPerfil() {
        self::logNavegacion();
        $this->layout = 'complete/main';

        if (Yii::$app->user->isGuest) {
            $this->redirect('login');
        } else {
            Yii::$app->params['layout.title'] = Yii::t('app', 'myaccount');
            $model = \app\modules\accesos\models\RBACUsuarios::find()->where(['id_rbac_usuario'=>\Yii::$app->user->identity->id_rbac_usuario])->one();

            return $this->render('perfil', [
                        'model' => $model,
            ]);

        }
    }

    public function actionError()
    {
        if (Yii::$app->user->isGuest) {
        }
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }
}

views/site/about.php
<?php


use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/change_password.php
<?php


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;


Yii::$app->params['MenuModule'] = [
    [
        'label' => '<i class="fa fa-user"></i> ' . Yii::t('app','myaccount'),
        'encodeLabels' => false,
        'url' => ['site/perfil'],
    ],    
];
?>
<div class="col-lg-6">
    <section class="box nobox">
            <div class="content-body">    
                <div class="row">
                    <div class="col-md-12" style="padding: 0 15px">
                        <div class="usuario-perfil panel panel-default">
                            <div class="panel-heading navbar-tool">
                                <h3 class="panel-title"><?= Yii::t('app','change_password') ?></h3>
                                <div class="menu-tool">
                                    <div class="menu-items">
                                        <?=  \app\models\MenuMain::menu(); ?>
                                    </div>
                                </div>          
                            </div>
                            <div class="panel-body">



                                        <?php $form = ActiveForm::begin(['id' => 'changepassword-form']); ?>

                                            <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                                            <?= $form->field($model, 'password_new')->passwordInput() ?>

                                            <?= $form->field($model, 'password_repeat')->passwordInput() ?>

                                            <div class="form-group">
                                                <?= Html::submitButton(Yii::t('app',Yii::$app->params['text.save']), ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                                            </div>

                                        <?php ActiveForm::end(); ?>

                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
</div>
<div class="col-lg-6">
    <section class="box nobox">
            <div class="content-body">    
                <div class="row">
                    <div class="col-md-12" style="padding: 0 15px">
                        <div class="usuario-perfil panel panel-default">
                            <div class="panel-heading navbar-tool">
                                <h3 class="panel-title"><?= Yii::t('app','security_advice') ?></h3>         
                            </div>
                            <div class="panel-body">
                                <div class="alert alert-info alert-dismissible fade in">
                                    <p class="text-left"><?= Yii::t('app','password_character') ?></p>
                                    <p class="text-left"><?= Yii::t('app','password_letter') ?></p>
                                    <p class="text-left"><?= Yii::t('app','password_number') ?></p>
                                </div>
                                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
</div>

views/site/contact.php
<?php


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php


use yii\helpers\Html;
$this->title = @$exception->statusCode;
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <section class="box nobox ">
                <div class="content-body">    
                    <div class="row">
                        <div class="col-xs-12">

                            <h1 class="page_error_code text-primary"><?= Html::encode($this->title) ?></h1>
                            <h1 class="page_error_info"><?= nl2br(Html::encode($exception->getMessage())) ?></h1>
                             <div class="row">
                                <div class="col-md-offset-3 col-sm-offset-3 col-xs-offset-2 col-xs-8 col-sm-6">
                                    <form action="javascript:;" method="post" class="page_error_search">
                                        <div class="text-center page_error_btn">
                                            <a class="btn btn-primary btn-lg" href='<?php echo Yii::getAlias('@web/') ?>'><i class='fa fa-location-arrow'></i> &nbsp; Inicio</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

views/site/index.php
<?php 
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

echo '<h1>Módulos Principales</h1>';
?>
<div class="col-lg-12">
    <section class="box nobox">
            <div class="content-body">    
                <div class="row">
                    <div class="col-md-12" >
                        <div class="usuario-perfil panel panel-default">
                            
                                <h3 class="panel-title"><?= Yii::t('app','title_home') ?></h3>
                                <div class="menu-tool">
                                    <div class="menu-items">
                                        <?=  \app\models\MenuMain::menu(); ?>

                                    </div>
                                </div>          
                           
                            <div class="panel-body">
								<div class="col-lg-6 col-xs-6">
								          <div class="small-box bg-default">
								            <div class="inner">

								              <p class="ico-home"><?= Yii::t('app','title_maquina') ?></p>
								            </div>
								            <div class="icon">
								              <i class="g glyphicon glyphicon-hdd"></i>
								            </div>
								            <a href="../admin/maquina/create" class="small-box-footer">Registrar Nueva <i class="fa fa-arrow-circle-right"></i></a>
								          </div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;
use yii\helpers\Url;

$this->title = 'Acceso';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <?php 
        Modal::begin([
            // 'header'=>'register',
            'id'=>'modal',
            'size'=>'modal-lg',
        ]);

        echo "<div id='modalContent'></div>";

        Modal::end();
    ?>
    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>Login</b>Usuarios</a>
        </div>
        <div class="login-box-body">
            <p class="login-box-msg">Ingresar Usuario</p>

                <?php $form = ActiveForm::begin([
                    'id' => 'login-form',
                    'layout' => 'horizontal',
                    'fieldConfig' => [
                        'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                        'labelOptions' => ['class' => 'col-lg-1 control-label'],
                    ],
                ]); ?>

                    <?= $form->field(
                        $model,
                        'username',
                        [
                            'options' =>
                                [
                                'tag' => 'div',
                                'class' => 'form-group field-loginform-username has-feedback required'
                            ],
                            'template' => '{input}<span class="glyphicon glyphicon-user form-control-feedback"></span>
                                             {error}{hint}'
                        ]
                    )->textInput(['placeholder' => 'usuario'])
                    ?>

                    <?= $form->field(
                        $model,
                        'password',
                        [
                            'options' =>
                                [
                                'tag' => 'div',
                                'class' => 'form-group field-loginform-password has-feedback required'
                            ],
                            'template' => '{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                               {error}{hint}'
                        ]
                    )->passwordInput(['placeholder' => 'contraseña']) ?>




                    <div class="form-group">
                        <div class="col-lg-offset-1 col-lg-11">
                            <?= Html::submitButton('ingresar', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                            <br><br>
                            <!-- <//?= Html::a('recuperar contraseña', ['#'], ['class' => 'profile-link']) ?> -->
                        </div>
                    </div>

                <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/login2.php
<?php


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Acceso';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>


    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    
</div>

views/site/old_login.php
<?php


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

 <div class="login-wrapper row">
        <div id="login" class="login loginpage col-lg-offset-4 col-md-offset-3 col-sm-offset-3 col-xs-offset-0 col-xs-12 col-sm-6 col-lg-4">
            <h1><a href="#" title="Login Page" tabindex="-1"></a></h1>

          <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'fieldConfig' => [
            'labelOptions' => ['class' => ''],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'class'=>'input']) ?>

        <?= $form->field($model, 'password')->passwordInput(['class'=>'input']) ?>


        <div class="form-group">
            <div >
                <?= Html::submitButton('Ingresar', ['class' => 'btn btn-accent btn-block', 'name' => 'login-button', 'id'=>'wp-submit']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
              


        </div>
    </div>

 

   
</div>

views/site/perfil.php
<?php

use yii\helpers\Html;


Yii::$app->params['MenuModule'] = [
    [
        'label' => '<i class="fa fa-key"></i> ' . Yii::t('app','change_password'),
        'encodeLabels' => false,
        'url' => ['site/cambiar_contrasena'],
    ],
];
?>

<div class="col-lg-12">
    <section class="box nobox">
        <div class="content-body">
            <div class="row">
                <div class="col-md-12" style="padding: 0 15px">
                    <div class="usuario-perfil panel panel-default">
                        <div class="panel-heading navbar-tool">
                            <h3 class="panel-title"><?= Yii::t('app','profile') ?></h3>
                            <div class="menu-tool">
                                <div class="menu-items">
                                    <?=  \app\models\MenuMain::menu(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <th rowspan="7" width="35%" style="border-top: none;">
                                        <div class="uprofile-image">
                                            <img alt="" src="<?= Yii::getAlias('@web/images/avatar1.jpg') ?>" class="img-responsive">
                                        </div>
                                        <div class="uprofile-name">
                                            <h3>
                                                <a href="#"><?= $model->nombre?> <?= $model->apellido?></a>
                                                <span class="uprofile-status online"></span>
                                            </h3>
                                            <p class="uprofile-title"><?= $model->rol->descripcion?></p>
                                        </div>
                                    </th>
                                </tr>
                                <tr>
                                    <th style="border-top: none;"><?= Yii::t('app','username') ?></th>
                                    <td style="border-top: none;"><?= $model->nombreusuario ?></td>
                                </tr>
                                <tr>
                                    <th style="border-top: none;"><?= Yii::t('app','last_login') ?></th>
                                    <td style="border-top: none;">
                                        <?php $fecha = $model->lastlogin_time == null ? Yii::$app->session['lastlogin'] :  $model->lastlogin_time;?>
                                        <?= Yii::$app->formatter->asDate($fecha, Yii::$app->params['format.date']) ?> a las
                                        <?= Yii::$app->formatter->asDate($fecha. ' ' .Yii::$app->getTimeZone() ,'php:h:iA'); ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th style="border-top: none;"><?= Yii::t('app','name') ?> <?= Yii::t('app','last_name') ?></th>
                                    <td style="border-top: none;"><?= $model->nombre ?> <?= $model->apellido ?></td>
                                </tr>
                                <tr>
                                    <th style="border-top: none;"><?= Yii::t('app','dni_number') ?>/<?= Yii::t('app','tax_id_number') ?></th>
                                    <td style="border-top: none;"><?= $model->dni_letra ?>-<?= $model->dni_numero ?></td>
                                </tr>
                                <tr>
                                    <th style="border-top: none;"><?= Yii::t('app','email') ?></th>
                                    <td style="border-top: none;"><?= $model->email ?></td>
                                </tr>
                                <tr>
                                    <th style="border-top: none;"><?= Yii::t('app','phone') ?></th>
                                    <td style="border-top: none;"><?= $model->telf_local_numero ?></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

views/site/recoverpass.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
 
<h3><?= $msg ?></h3>
 
<h1>Recover Password</h1>
<?php $form = ActiveForm::begin([
    'method' => 'post',
    'enableClientValidation' => true,
]);
?>
 
<div class="form-group">
 <?= $form->field($model, "email")->input("email") ?>  
</div>
 
<?= Html::submitButton("Recover Password", ["class" => "btn btn-primary"]) ?>
 
<?php $form->end() ?>

views/site/resetpass.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
 
<h3><?= $msg ?></h3>
 
<h1>Reset Password</h1>
<?php $form = ActiveForm::begin([
    'method' => 'post',
    'enableClientValidation' => true,
]);
?>

<div class="form-group">
 <?= $form->field($model, "email")->input("email") ?>  
</div>
 
<div class="form-group">
 <?= $form->field($model, "password")->input("password") ?>  
</div>
 
<div class="form-group">
 <?= $form->field($model, "password_repeat")->input("password") ?>  
</div>

<div class="form-group">
 <?= $form->field($model, "verification_code")->input("text") ?>  
</div>

<div class="form-group">
 <?= $form->field($model, "recover")->input("hidden")->label(false) ?>  
</div>
 
<?= Html::submitButton("Reset password", ["class" => "btn btn-primary"]) ?>
 
<?php $form->end() ?>